
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: webapp-namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>


kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=aaaaaarteeeem --docker-password=******* --docker-email=******* --namespace=webapp-namespace --dry-run=client -o yaml
